// Development-only weekly input. Never persist this module to SQLite or projections.
export const weeklyDashboardFixture = Object.freeze({
  fixture: true,
  fixtureLabel: 'Synthetic fixture',
  source: {
    fixture: true,
    kind: 'synthetic_fixture',
    authority: false,
  },
  schemaVersion: 1,
  week: {
    fixture: true,
    startDate: '2026-08-03',
    endDate: '2026-08-09',
    throughDate: '2026-08-06',
    recordedDays: 3,
    elapsedDays: 4,
  },
  bodyComposition: {
    fixture: true,
    bodyFatPercent: {
      fixture: true,
      label: 'Body fat',
      unit: '%',
      status: 'recorded',
      confidence: 'medium',
      observations: [
        { fixture: true, date: '2026-06-15', value: 29.2 },
        { fixture: true, date: '2026-07-13', value: 28.6 },
        { fixture: true, date: '2026-08-05', value: 27.8 },
      ],
    },
    fatMassKg: {
      fixture: true,
      label: 'Fat mass',
      unit: 'kg',
      status: 'recorded',
      confidence: 'medium',
      observations: [
        { fixture: true, date: '2026-06-15', value: 15.6 },
        { fixture: true, date: '2026-07-13', value: 15.1 },
        { fixture: true, date: '2026-08-05', value: 14.7 },
      ],
    },
    skeletalMuscleKg: {
      fixture: true,
      label: 'Skeletal muscle',
      unit: 'kg',
      status: 'recorded',
      confidence: 'medium',
      observations: [
        { fixture: true, date: '2026-06-15', value: 19.4 },
        { fixture: true, date: '2026-07-13', value: 19.7 },
        { fixture: true, date: '2026-08-05', value: 20.1 },
      ],
    },
    waistHipRatio: {
      fixture: true,
      label: 'Waist–hip ratio',
      unit: null,
      status: 'missing',
      confidence: 'unknown',
      observations: [],
    },
    weightKg: {
      fixture: true,
      label: 'Weight',
      unit: 'kg',
      status: 'recorded',
      confidence: 'medium',
      observations: [
        { fixture: true, date: '2026-06-15', value: 53.1 },
        { fixture: true, date: '2026-07-13', value: 52.8 },
        { fixture: true, date: '2026-08-05', value: 52.9 },
      ],
    },
  },
  training: {
    fixture: true,
    status: 'needs_review',
    completedSessions: 3,
    plannedSessions: 4,
    recordedMinutes: 142,
    loadVolumeKg: 1860,
    loadCoverage: { fixture: true, recorded: 2, expected: 3 },
    note: 'One strength session is missing complete per-set load.',
  },
  nutrition: {
    fixture: true,
    status: 'needs_review',
    proteinGramsMedian: 74,
    proteinCoverage: { fixture: true, recorded: 3, elapsed: 4 },
    confidence: 'low',
    note: 'Meal estimates remain provisional until reviewed.',
  },
  recovery: {
    fixture: true,
    status: 'needs_review',
    sleepHoursAverage: 7.1,
    sleepCoverage: { fixture: true, recorded: 3, elapsed: 4 },
    energyAverage: 3.4,
    sorenessAverage: null,
    recoveryCoverage: { fixture: true, recorded: 2, elapsed: 4 },
    note: 'Soreness has not been recorded this week.',
  },
});

